/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotfoundRouteImport } from './routes/notfound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProductRouteImport } from './routes/dashboard/product'
import { Route as DashboardPaymentRouteImport } from './routes/dashboard/payment'
import { Route as DashboardOrderRouteImport } from './routes/dashboard/order'
import { Route as DashboardCategoryRouteImport } from './routes/dashboard/category'

const NotfoundRoute = NotfoundRouteImport.update({
  id: '/notfound',
  path: '/notfound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductRoute = DashboardProductRouteImport.update({
  id: '/dashboard/product',
  path: '/dashboard/product',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentRoute = DashboardPaymentRouteImport.update({
  id: '/dashboard/payment',
  path: '/dashboard/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrderRoute = DashboardOrderRouteImport.update({
  id: '/dashboard/order',
  path: '/dashboard/order',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCategoryRoute = DashboardCategoryRouteImport.update({
  id: '/dashboard/category',
  path: '/dashboard/category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notfound': typeof NotfoundRoute
  '/dashboard/category': typeof DashboardCategoryRoute
  '/dashboard/order': typeof DashboardOrderRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/product': typeof DashboardProductRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notfound': typeof NotfoundRoute
  '/dashboard/category': typeof DashboardCategoryRoute
  '/dashboard/order': typeof DashboardOrderRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/product': typeof DashboardProductRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notfound': typeof NotfoundRoute
  '/dashboard/category': typeof DashboardCategoryRoute
  '/dashboard/order': typeof DashboardOrderRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/product': typeof DashboardProductRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notfound'
    | '/dashboard/category'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notfound'
    | '/dashboard/category'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/notfound'
    | '/dashboard/category'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotfoundRoute: typeof NotfoundRoute
  DashboardCategoryRoute: typeof DashboardCategoryRoute
  DashboardOrderRoute: typeof DashboardOrderRoute
  DashboardPaymentRoute: typeof DashboardPaymentRoute
  DashboardProductRoute: typeof DashboardProductRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notfound': {
      id: '/notfound'
      path: '/notfound'
      fullPath: '/notfound'
      preLoaderRoute: typeof NotfoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/product': {
      id: '/dashboard/product'
      path: '/dashboard/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payment': {
      id: '/dashboard/payment'
      path: '/dashboard/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof DashboardPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/order': {
      id: '/dashboard/order'
      path: '/dashboard/order'
      fullPath: '/dashboard/order'
      preLoaderRoute: typeof DashboardOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/category': {
      id: '/dashboard/category'
      path: '/dashboard/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotfoundRoute: NotfoundRoute,
  DashboardCategoryRoute: DashboardCategoryRoute,
  DashboardOrderRoute: DashboardOrderRoute,
  DashboardPaymentRoute: DashboardPaymentRoute,
  DashboardProductRoute: DashboardProductRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
